/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpasRouteImport } from './routes/spas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as HireTermsRouteImport } from './routes/hire-terms'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SpasRoute = SpasRouteImport.update({
  id: '/spas',
  path: '/spas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const HireTermsRoute = HireTermsRouteImport.update({
  id: '/hire-terms',
  path: '/hire-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hire-terms': typeof HireTermsRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spas': typeof SpasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hire-terms': typeof HireTermsRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spas': typeof SpasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/hire-terms': typeof HireTermsRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spas': typeof SpasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/hire-terms'
    | '/service-area'
    | '/sitemap.xml'
    | '/spas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/hire-terms'
    | '/service-area'
    | '/sitemap.xml'
    | '/spas'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/hire-terms'
    | '/service-area'
    | '/sitemap.xml'
    | '/spas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  HireTermsRoute: typeof HireTermsRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpasRoute: typeof SpasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spas': {
      id: '/spas'
      path: '/spas'
      fullPath: '/spas'
      preLoaderRoute: typeof SpasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-terms': {
      id: '/hire-terms'
      path: '/hire-terms'
      fullPath: '/hire-terms'
      preLoaderRoute: typeof HireTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  HireTermsRoute: HireTermsRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpasRoute: SpasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
